<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdutosKitsSeeder extends Seeder
{
    public function run()
    {
        // Produtos iniciais (exemplo já existente)
        $produtosIniciais = [
            [
                'user_id'             => null,
                'codigo'              => 'MK001',
                'codigos_alternativos'=> json_encode(['MK-A001']),
                'nome'                => 'Batom Satin Lips Vermelho',
                'marca'               => 'Mary Kay',
                'preco'               => 35.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Batom',
                'tonalidade'          => 'Vermelho',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/batom_vermelho.jpg',
                'descricao'           => 'Batom com alta pigmentação e longa duração.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK002',
                'codigos_alternativos'=> null,
                'nome'                => 'Base Facial Liquid Matte',
                'marca'               => 'Mary Kay',
                'preco'               => 50.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Base',
                'tonalidade'          => 'Neutra',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/base_matte.jpg',
                'descricao'           => 'Base líquida com acabamento matte.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
        ];

        DB::table('produtos')->insert($produtosIniciais);

        // Gerando mais 15 produtos de exemplo
        $produtosExtra = [
            [
                'user_id'             => null,
                'codigo'              => 'MK003',
                'codigos_alternativos'=> null,
                'nome'                => 'Pó Compacto Translúcido',
                'marca'               => 'Mary Kay',
                'preco'               => 40.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Pó Compacto',
                'tonalidade'          => 'Translúcido',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/po_translucido.jpg',
                'descricao'           => 'Pó compacto que uniformiza e suaviza a pele.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK004',
                'codigos_alternativos'=> null,
                'nome'                => 'Máscara de Cílios Volumizing',
                'marca'               => 'Mary Kay',
                'preco'               => 30.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Máscara de Cílios',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/mascara_cilios.jpg',
                'descricao'           => 'Máscara que proporciona volume e definição aos cílios.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK005',
                'codigos_alternativos'=> null,
                'nome'                => 'Delineador Líquido Preto',
                'marca'               => 'Mary Kay',
                'preco'               => 25.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Delineador',
                'tonalidade'          => 'Preto',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/delineador_liquido.jpg',
                'descricao'           => 'Delineador líquido para traços precisos e marcantes.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK006',
                'codigos_alternativos'=> null,
                'nome'                => 'Sombra em Pó Intensidade',
                'marca'               => 'Mary Kay',
                'preco'               => 45.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Sombra',
                'tonalidade'          => 'Diversas',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/sombra_pó.jpg',
                'descricao'           => 'Sombra em pó com alta pigmentação e longa duração.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK007',
                'codigos_alternativos'=> null,
                'nome'                => 'Blush Natural',
                'marca'               => 'Mary Kay',
                'preco'               => 28.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Blush',
                'tonalidade'          => 'Rosa',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/blush_natural.jpg',
                'descricao'           => 'Blush com acabamento natural para um toque de cor delicado.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK008',
                'codigos_alternativos'=> null,
                'nome'                => 'Iluminador Facial',
                'marca'               => 'Mary Kay',
                'preco'               => 32.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Iluminador',
                'tonalidade'          => 'Dourado',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/iluminador.jpg',
                'descricao'           => 'Iluminador para realçar pontos estratégicos do rosto.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK009',
                'codigos_alternativos'=> null,
                'nome'                => 'Primer Facial',
                'marca'               => 'Mary Kay',
                'preco'               => 38.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Primer',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/primer_facial.jpg',
                'descricao'           => 'Primer para preparar a pele e prolongar a durabilidade da maquiagem.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK010',
                'codigos_alternativos'=> null,
                'nome'                => 'Hidratante Facial Day Cream',
                'marca'               => 'Mary Kay',
                'preco'               => 55.00,
                'categoria'           => 'Cuidados com a Pele',
                'subcategoria'        => 'Hidratante',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/day_cream.jpg',
                'descricao'           => 'Hidratante facial para uso diurno com proteção leve.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK011',
                'codigos_alternativos'=> null,
                'nome'                => 'Hidratante Facial Night Cream',
                'marca'               => 'Mary Kay',
                'preco'               => 60.00,
                'categoria'           => 'Cuidados com a Pele',
                'subcategoria'        => 'Hidratante',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/night_cream.jpg',
                'descricao'           => 'Hidratante facial para uso noturno com ação regeneradora.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK012',
                'codigos_alternativos'=> null,
                'nome'                => 'Tônico Facial Refrescante',
                'marca'               => 'Mary Kay',
                'preco'               => 22.00,
                'categoria'           => 'Cuidados com a Pele',
                'subcategoria'        => 'Tônico',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/tonico.jpg',
                'descricao'           => 'Tônico facial para refrescar e equilibrar a pele.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK013',
                'codigos_alternativos'=> null,
                'nome'                => 'Esfoliante Facial Suave',
                'marca'               => 'Mary Kay',
                'preco'               => 27.00,
                'categoria'           => 'Cuidados com a Pele',
                'subcategoria'        => 'Esfoliante',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/esfoliante.jpg',
                'descricao'           => 'Esfoliante facial que remove impurezas e células mortas.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK014',
                'codigos_alternativos'=> null,
                'nome'                => 'Máscara de Tratamento Capilar',
                'marca'               => 'Mary Kay',
                'preco'               => 48.00,
                'categoria'           => 'Cuidados com o Cabelo',
                'subcategoria'        => 'Máscara Capilar',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/mascara_capilar.jpg',
                'descricao'           => 'Máscara para tratamento intensivo e reparação capilar.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK015',
                'codigos_alternativos'=> null,
                'nome'                => 'Creme para Mãos Nutritivo',
                'marca'               => 'Mary Kay',
                'preco'               => 18.00,
                'categoria'           => 'Cuidados com as Mãos',
                'subcategoria'        => 'Creme para Mãos',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/creme_maos.jpg',
                'descricao'           => 'Creme nutritivo que hidrata e protege as mãos.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK016',
                'codigos_alternativos'=> null,
                'nome'                => 'Lápis de Sobrancelha',
                'marca'               => 'Mary Kay',
                'preco'               => 15.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Sobrancelha',
                'tonalidade'          => 'Castanho',
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/lapis_sobrancelha.jpg',
                'descricao'           => 'Lápis para sobrancelhas com acabamento natural e duradouro.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'user_id'             => null,
                'codigo'              => 'MK017',
                'codigos_alternativos'=> null,
                'nome'                => 'Fixador de Maquiagem',
                'marca'               => 'Mary Kay',
                'preco'               => 20.00,
                'categoria'           => 'Maquiagem',
                'subcategoria'        => 'Fixador',
                'tonalidade'          => null,
                'eh_kit'              => false,
                'foto'                => 'imagens/produtos/fixador_maquiagem.jpg',
                'descricao'           => 'Spray fixador que prolonga a durabilidade da maquiagem.',
                'ativo'               => true,
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
        ];

        DB::table('produtos')->insert($produtosExtra);

        // Exemplo de inserção de um KIT (utilizando os produtos MK001 e MK002)
        $batom = DB::table('produtos')->where('codigo', 'MK001')->first();
        $base   = DB::table('produtos')->where('codigo', 'MK002')->first();

        $kitId = DB::table('produtos')->insertGetId([
            'user_id'             => null,
            'codigo'              => 'KIT001',
            'codigos_alternativos'=> json_encode([]),
            'nome'                => 'Kit Completo de Maquiagem Mary Kay',
            'marca'               => 'Mary Kay',
            'preco'               => 80.00,
            'categoria'           => 'Kit',
            'subcategoria'        => null,
            'tonalidade'          => null,
            'eh_kit'              => true,
            'foto'                => 'imagens/produtos/kit_maquiagem.jpg',
            'descricao'           => 'Kit composto por Batom Satin Lips Vermelho e Base Facial Liquid Matte.',
            'ativo'               => true,
            'created_at'          => now(),
            'updated_at'          => now(),
        ]);

        $kitComponentes = [
            [
                'kit_id'      => $kitId,
                'produto_id'  => $batom->id,
                'quantidade'  => 1,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'kit_id'      => $kitId,
                'produto_id'  => $base->id,
                'quantidade'  => 1,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ];

        DB::table('kit_produtos')->insert($kitComponentes);
    }
}
